[application]

[web.app]

# HTML title tag content
title = "zhiyanzhaijie"

[web.resource]
asset_dir = "assets"
base_path = "/"
# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.dev-server]
asset_dir = "assets"

[web.watcher]
watch_path = []

[web.resource.dev]
script = []
