[application]
assets_dir = "assets"

[components]
components_dir = "src/components/ui"

[web.app]
title = "zhiyanzhaijie"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web.wasm_opt]
level = "z"
debug = false
keep_names = false
memory_packing = true
extra_features = ["--converge"]

[web]
pre_compress = true
resource_strategy = "aggressive"
