[application]

[web.app]

# HTML title tag content
title = "脂砚斋介"

[web.resource]
asset_dir = "assets"
base_path = "/"
# Additional CSS style files
style = []

# Additional JavaScript files
script = []


[web.dev-server]
# The directory to serve static assets from.
asset_dir = "assets"

[web.watcher]
# The files & directories to monitor for changes
watch_path = ["src", "src/md"]

[web.resource.dev]
# Javascript code file
# serve: [dev-server] only
script = []
