[application]
assets_dir = "assets"

[components]
components_dir = "src/components/ui"

[web.app]
title = "zhiyanzhaijie"

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[web.wasm_opt]
level = "0"
debug = true
keep_names = true

[web.watcher]
index_on_404 = true
watch_path = ["src"]
